ElderLists/FileCatalog/Models/PostsViewModels.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace FileCatalog.Models
{
    public class PostHeaderBaseViewModel
    {
        [Display(Name = "ID")]
        public int Id { get; set; }

        [Display(Name = "Заголовок")]
        public string Header { get; set; }
    }

    public class PostHeaderViewModel : PostHeaderBaseViewModel
    {
        [Display(Name = "Скрыт")]
        public bool IsHidden { get; set; }

        [Display(Name = "Создано")]
        public DateTime CreationDate { get; set; }

        [Display(Name = "Отредактировано")]
        public DateTime? LastEditDate { get; set; }

        [Display(Name = "ID Автора")]
        public int AuthorId { get; set; }

        [Display(Name = "Автор")]
        public string Author { get; set; }

        [Display(Name = "ID Редактора")]
        public int? EditorId { get; set; }

        [Display(Name = "Редактор")]
        public string Editor { get; set; }
    }

    public class PostDetailsViewModel : PostHeaderViewModel
    {
        [Display(Name = "Текст")]
        public string Text { get; set; }

        [Display(Name = "Важно")]
        public bool IsImportant { get; set; }

        [Display(Name = "Исправления")]
        public IList<EditionViewModel> Editions { get; set; }

        [Display(Name = "Прикрепленные файлы")]
        public IList<FileViewModel> Files { get; set; }
    }

    public class PostsHeadersListsViewModel
    {
        [Display(Name = "Важные")]
        public IList<PostHeaderViewModel> Important { get; set; }

        [Display(Name = "Остальные")]
        public IPagedList<PostHeaderViewModel> Common { get; set; }
    }

    public class NewPostViewModel
    {
        [Required]
        [StringLength(128)]
        [Display(Name = "Заголовок")]
        public string Header { get; set; }

        [Required]
        [StringLength(2048)]
        [DataType(DataType.MultilineText)]
        [Display(Name = "Текст")]
        public string Text { get; set; }

        [Display(Name = "Скрыть")]
        public bool IsHidden { get; set; }

        [Display(Name = "Важно")]
        public bool IsImportant { get; set; }
    }

    public class EditPostViewModel : NewPostViewModel
    {
        [Display(Name = "ID")]
        public int Id { get; set; }

        [Required]
        [StringLength(512)]
        [Display(Name = "Замечания об исправлении")]
        public string Note { get; set; }

        [Display(Name = "Файлы")]
        public IEnumerable<FileEditViewModel> CurrentFiles { get; set; }
    }

    public class EditionViewModel
    {
        [Display(Name = "Дата")]
        public DateTime Date { get; set; }

        [Display(Name = "Исправление")]
        public string Note { get; set; }

        [Display(Name = "ID Редактора")]
        public int EditorId { get; set; }

        [Display(Name = "Отредактировал")]
        public string Editor { get; set; }
    }
}

ElderLists/FileCatalog/Controllers/PostsController.cs
using FileCatalog.Extensions;
using FileCatalog.Models;
using FileCatalog.Repositories;
using FileCatalogDatabase;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace FileCatalog.Controllers
{
    public class PostsController : Controller
    {
        private PostsRepository repository = new PostsRepository();

        public async Task<ActionResult> Index(string search, int? page)
        {
            int? userId = User.Identity.IsAuthenticated ? (int?)User.Identity.GetUserId<int>() : null;
            var options = new PagedListOptions(search, page);
            if (userId == null || await repository.Context.IsUserNotBannedAsync((int)userId))
            {
                ViewBag.Search = search;
                return View(await repository.CreateHeadersListModelAsync(userId, null, options));
            }
            else
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
        }

        public async Task<ActionResult> Details(int id)
        {
            if (! await repository.PostExistsAsync(id))
                return new HttpNotFoundResult();

            if (!User.Identity.IsAuthenticated || await repository.Context.IsUserNotBannedAsync(User.Identity.GetUserId<int>()))
                return View(await repository.CreateDetailsModelAsync(id));
            else
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
        }

        [Authorize]
        public async Task<ActionResult> New()
        {
            if (await repository.UserCanCreateAsync(User.Identity.GetUserId<int>()))
                return View();
            else
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> New([Bind(Include = "Header,Text,IsHidden,IsImportant")] NewPostViewModel model, IEnumerable<HttpPostedFileBase> files)
        {
            int userId = User.Identity.GetUserId<int>();
            if (await repository.UserCanCreateAsync(userId))
            {
                if (await repository.IsHeaderAlreadyInUseAsync(model.Header))
                    ModelState.AddModelError("", repository.HeaderAlreadyInUseMessage());

                if (ModelState.IsValid)
                {
                    if (model.IsImportant && !(await repository.Context.IsUserInRoleAsync(userId, "Moderator")))
                        return new HttpStatusCodeResult(HttpStatusCode.Forbidden);

                    var path = Server.MapPath("~/UploadedFiles/");
                    await repository.AddNewPostAsync(userId, path, model, files);
                    return RedirectToAction("Index");
                }
                else
                    return View(model);
            }
            else
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
        }

        [Authorize]
        public async Task<ActionResult> Edit(int id)
        {
            if (await repository.PostExistsAsync(id))
            {
                if (await repository.UserCanEditAsync(User.Identity.GetUserId<int>(), id))
                    return View(await repository.CreateEditModelAsync(id));
                else
                    return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
            }
            else
                return new HttpNotFoundResult();
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Header,Text,IsHidden,IsImportant,Note")] EditPostViewModel model, IEnumerable<FileEditViewModel> currentFiles, IEnumerable<HttpPostedFileBase> newFiles)
        {
            int userId = User.Identity.GetUserId<int>();
            if (await repository.UserCanEditAsync(userId, model.Id))
            {
                model.CurrentFiles = currentFiles ?? new List<FileEditViewModel>(); // HAIL SATAN

                if (await repository.IsHeaderAlreadyInUseAsync(model.Header, model.Id))
                    ModelState.AddModelError("", repository.HeaderAlreadyInUseMessage());

                if (ModelState.IsValid)
                {
                    if (model.IsImportant && !(await repository.Context.IsUserInRoleAsync(userId, "Moderator")))
                        return new HttpStatusCodeResult(HttpStatusCode.Forbidden);

                    var path = Server.MapPath("~/UploadedFiles/");
                    await repository.EditPostAsync(userId, path, model, newFiles);
                    return RedirectToAction("Index");
                }
                else
                    return View(model);
            }
            else
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
        }

        [Authorize]
        public async Task<ActionResult> My(string search, int? page)
        {
            int userId = User.Identity.GetUserId<int>();
            if (await repository.Context.IsUserNotBannedAsync(userId))
            {
                ViewBag.Search = search;
                return View(await repository.CreateHeadersListModelAsync(userId, userId, new PagedListOptions(search, page)));
            }
            else
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
        }

        public async Task<ActionResult> UserPosts(int id, string search, int? page)
        {
            int userId = User.Identity.GetUserId<int>();
            if (await repository.Context.IsUserNotBannedAsync(userId))
            {
                var userName = await repository.Context.GetUserNameAsync(id);
                if (userName == null)
                    return new HttpNotFoundResult();
                else
                {
                    ViewBag.UserName = userName;
                    ViewBag.UserId = userId;
                    ViewBag.Search = search;
                    return View(await repository.CreateHeadersListModelAsync(userId, id, new PagedListOptions(search, page)));
                }
            }
            else
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
        }

        [Authorize]
        public async Task<ActionResult> Download(int id)
        {
            int userId = User.Identity.GetUserId<int>();
            if (await repository.IsUserCanDownloadAsync(userId))
            {
                var path = Server.MapPath("~/UploadedFiles/");
                if (await repository.FileExistsAsync(id, path))
                {
                    Tuple<byte[], string> fileData = await repository.GetFileDataAsync(userId, id, path);
                    return File(fileData.Item1, System.Net.Mime.MediaTypeNames.Application.Octet, fileData.Item2);
                }
                else
                    return new HttpNotFoundResult();
            }
            else
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
        }

        [Authorize]
        public async Task<ActionResult> Delete(int id)
        {
            int userId = User.Identity.GetUserId<int>();
            if (await repository.UserCanDeleteAsync(userId, id))
                return View(await repository.GetPostHeaderBaseModelAsync(id));
            else
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(PostHeaderBaseViewModel model)
        {
            int userId = User.Identity.GetUserId<int>();
            if (await repository.UserCanDeleteAsync(userId, model.Id))
            {
                await repository.DeletePostAsync(userId, model.Id);
                return RedirectToAction("Index");
            }
            else
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                repository.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ElderLists/FileCatalog/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FileCatalogDatabase;
using FileCatalogDatabase.Models.Identity;
using FileCatalog.Models;
using Microsoft.AspNet.Identity;
using FileCatalog.Extensions;
using FileCatalog.Repositories;

namespace FileCatalog.Controllers
{
    public class UsersController : Controller
    {
        private UsersRepository repository = new UsersRepository();

        public async Task<ActionResult> Index(string search, int? page)
        {
            if (User.Identity.IsAuthenticated && await repository.Context.IsUserBannedAsync(User.Identity.GetUserId<int>()))
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);

            ViewBag.Search = search;
            return View(await repository.GetUsersListAsync("User", new PagedListOptions(search, page)));
        }
        
        public async Task<ActionResult> Moderators(string search, int? page)
        {
            if (User.Identity.IsAuthenticated && await repository.Context.IsUserBannedAsync(User.Identity.GetUserId<int>()))
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);

            ViewBag.Search = search;
            return View(await repository.GetUsersListAsync("Moderator", new PagedListOptions(search, page)));
        }

        public async Task<ActionResult> Banned(string search, int? page)
        {
            if (User.Identity.IsAuthenticated && await repository.Context.IsUserBannedAsync(User.Identity.GetUserId<int>()))
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);

            ViewBag.Search = search;
            return View(await repository.GetUsersListAsync("Banned", new PagedListOptions(search, page)));
        }

        [Authorize]
        public ActionResult My()
        {
            return RedirectToAction("Details", new { id = User.Identity.GetUserId<int>() });
        }

        public async Task<ActionResult> Details(int id)
        {
            if (User.Identity.IsAuthenticated && await repository.Context.IsUserBannedAsync(User.Identity.GetUserId<int>()))
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);

            return View(await repository.GetUserDetailsAsync(id));
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                repository.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ElderLists/FileCatalog/Views/Posts/Delete.cshtml
@model FileCatalog.Models.PostHeaderBaseViewModel

<h2>Удаление публикации</h2>

@using (Html.BeginForm("Delete", "Posts", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.Id)

    <p>Вы действительно хотите удалить публикацию <b>@Model.Header</b>?</p>
    <p>
        @Html.ActionLink("Назад", "Details", "Posts", new { @id = Model.Id }, new { @class = "btn btn-default" })
        <input type="submit" value="Удалить" class="btn btn-danger" />
    </p>
}

ElderLists/FileCatalog/Views/Posts/Details.cshtml
@model FileCatalog.Models.PostDetailsViewModel
@using FileCatalog.Extensions
@using Microsoft.AspNet.Identity
@{ 
    bool userLoggedIn = User.Identity.IsAuthenticated;
    bool userAuthor = User.IsInRole("User") && User.Identity.GetUserId<int>() == Model.AuthorId;
    bool userModerator = User.IsInRole("Moderator");
    bool userAdmin = User.IsInRole("Admin");
}

<div class="form-horizontal">
    <div class="form-group">
        <h2>@Model.Header</h2>

        <div class="form-group">
            @Html.LabelFor(model => model.Author, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-8">
                <div class="form-control-static">
                    <p>@Html.DisplayFor(model => model.Author)</p>
                    <p>@Html.ActionLink("Страница пользователя", "Details", "Users", new { id = Model.AuthorId }, htmlAttributes: new { @class = "btn btn-default" })</p>
                </div>               
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreationDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-8">
                <div class="form-control-static">
                    @Html.DisplayFor(model => model.CreationDate)
                </div>
            </div>
        </div>

        @if (Model.IsHidden || Model.IsImportant)
        {
            <div class="form-group">
                <label class="control-label col-md-2">Метки</label>
                <div class="col-md-8">
                    <div class="form-control-static">
                        @if (Model.IsImportant)
                        {
                            <p>Важно</p>
                        }
                        @if (Model.IsHidden)
                        {
                            <p>Cкрыто</p>
                        }
                    </div>
                </div>
            </div>
        }

        @if (Model.Editions.Any())
        {
            <div class="form-group">
                @Html.LabelFor(model => model.Editions, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-8">
                    <div class="form-control-static">
                        <table class="table">
                            <tr>
                                <th>Дата</th>
                                <th>Редактор</th>
                                <th>Замечание</th>
                            </tr>
                            @foreach (var item in Model.Editions)
                            {
                                <tr>
                                    <td>@Html.DisplayFor(modelItem => item.Date)</td>
                                    <td>@Html.DisplayFor(modelItem => item.Editor)</td>
                                    <td>@Html.DisplayFor(modelItem => item.Note)</td>
                                </tr>
                            }
                        </table>
                    </div>
                </div>
            </div>
        }

        <div class="form-group">
            @Html.LabelFor(model => model.Text, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-8">
                <div class="form-control-static">
                    @Html.DisplayMultilineFor(model => model.Text)
                </div>
            </div>
        </div>

        @if (Model.Files.Any())
        {
        <div class="form-group">
            @Html.LabelFor(model => model.Files, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-8">
                <div class="form-control-static">
                    @if (!userLoggedIn)
                    {
                        <p>Внимание! Скачивание доступно только зарегистрированным пользователям.</p>
                    }
                    <table class="table">
                        <tr>
                            <th>Файл</th>
                            <th>Дата загрузки</th>
                            <th>Последнее скачивание</th>
                            <th>Всего скачиваний</th>
                            <th></th>
                        </tr>
                    @foreach (var item in Model.Files)
                    {
                        <tr>
                            <td>@Html.DisplayFor(modelItem => item.Name)</td>
                            <td>@Html.DisplayFor(modelItem => item.UploadDate)</td>
                            <td>@Html.DisplayFor(modelItem => item.LastDownloadDate)</td>
                            <td>@Html.DisplayFor(modelItem => item.DownloadsCount)</td>
                            @if (userLoggedIn)
                            {
                                <td>@Html.ActionLink("Скачать", "Download", new { id = item.Id }, htmlAttributes: new { @class = "btn btn-default" })</td>
                            }
                        </tr>
                    }
                    </table>
                </div>
            </div>
        </div>
        }

        @if (userAuthor || userModerator || userAdmin)
        {
        <div class="form-group">
            <div class="col-md-offset-2">
                @if (userAuthor || userModerator)
                {
                    @Html.ActionLink("Исправить", "Edit", new { id = Model.Id }, htmlAttributes: new { @class = "btn btn-default" })
                }
                @if (userAuthor || userAdmin)
                {
                    @Html.ActionLink("Удалить", "Delete", new { id = Model.Id }, htmlAttributes: new { @class = "btn btn-default" })
                }
            </div>
        </div>
        }
    </div>
</div>

ElderLists/FileCatalog/Views/Posts/Edit.cshtml
@model FileCatalog.Models.EditPostViewModel
@using FileCatalog.Extensions

@{
    ViewBag.Title = "Новая публикация";
}

<h2>@ViewBag.Title</h2>
<hr />

@using (Html.BeginForm("Edit", "Posts", FormMethod.Post, new { role = "form", enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary("", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            <h3>Информация</h3>

            <div class="form-group">
                @Html.LabelFor(model => model.Header, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.Header, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Header, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Text, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.Text, new { htmlAttributes = new { @class = "form-control", @rows = 4 } })
                    @Html.ValidationMessageFor(model => model.Text, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Note, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.Note, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Note, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <h3>Метки</h3>

            <div class="form-group">
                @Html.LabelFor(model => model.IsHidden, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.IsHidden, new { htmlAttributes = new { @class = "form-control-static" } })
                </div>
            </div>

            @if (User.IsInRole("Moderator"))
            {
                <div class="form-group">
                    @Html.LabelFor(model => model.IsImportant, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-6">
                        @Html.EditorFor(model => model.IsImportant, new { htmlAttributes = new { @class = "form-control-static" } })
                    </div>
                </div>
            }
            else
            {
                @Html.HiddenFor(model => model.IsImportant)
            }
        </div>

        <div class="form-group">
            <h3>Файлы</h3>

            @if (Model.CurrentFiles.Any())
            {
            <div class="form-group">
                <label class="control-label col-md-2">Прикрепленные файлы</label>
                <div class="col-md-8">
                    <table class="table">
                        <tr>
                            <th>Файл</th>
                            <th>Дата загрузки</th>
                            <th>Последнее скачивание</th>
                            <th>Всего скачиваний</th>
                            <th>Удалить</th>
                        </tr>
                        @Html.EditorFor(model => model.CurrentFiles)
                    </table>
                </div>
            </div>
            }

            <div class="form-group">
                <label class="control-label col-md-2">Добавить файлы</label>
                <div class="col-md-8">
                    <input type="file" name="NewFiles" class="form-control-static" multiple />
                </div>
            </div>
        </div>
    </div>
    <div class="form-horizontal">
        <div class="form-group">
            <div class="col-md-offset-2">
                <input type="submit" value="Внести исправления" class="btn btn-default" />
            </div>
        </div>
    </div>
}

ElderLists/FileCatalog/Views/Posts/Index.cshtml
@model FileCatalog.Models.PostsHeadersListsViewModel
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "Публикации";
}

<h2>@ViewBag.Title</h2>
<p>
    @if (User.Identity.IsAuthenticated)
    {
        @Html.ActionLink("Мои публикации", "My", "Posts", routeValues: null, htmlAttributes: new { @class = "btn btn-default" })
    }
    @if (User.Identity.IsAuthenticated && User.IsInRole("User"))
    {
        @Html.ActionLink("Новая публикация", "New", "Posts", routeValues: null, htmlAttributes: new { @class = "btn btn-default" })
    }
</p>

@using (Html.BeginForm("Index", "Posts", FormMethod.Get))
{
    <p>
        Поиск по названию: @Html.TextBox("Search", ViewBag.Search as string)
        <input type="submit" value="Найти" />
    </p>
}

@if (Model.Important.Any())
{
    <h3>Важные</h3>
    @Html.Partial("PostHeadersTable", Model.Important)
    <br />

    <h3>Остальные</h3>
}
@Html.Partial("PostHeadersTable", Model.Common)

<br />
Страница @(Model.Common.PageCount < Model.Common.PageNumber ? 0 : Model.Common.PageNumber) из @Model.Common.PageCount

@Html.PagedListPager(Model.Common, page => Url.Action("Index", new { page, search = ViewBag.Search }))

ElderLists/FileCatalog/Views/Posts/My.cshtml
@model FileCatalog.Models.PostsHeadersListsViewModel
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "Мои публикации";
}

<h2>@ViewBag.Title</h2>
<p>
    @Html.ActionLink("Все публикации", "Index", "Posts", routeValues: null, htmlAttributes: new { @class = "btn btn-default" })
    @if (User.Identity.IsAuthenticated && User.IsInRole("User"))
    {
        @Html.ActionLink("Новая публикация", "New", "Posts", routeValues: null, htmlAttributes: new { @class = "btn btn-default" })
    }
</p>

@using (Html.BeginForm("My", "Posts", FormMethod.Get))
{
    <p>
        Поиск по названию: @Html.TextBox("Search", ViewBag.Search as string)
        <input type="submit" value="Найти" />
    </p>
}

@if (Model.Important.Any())
{
<h3>Важные</h3>
@Html.Partial("PostHeadersTable", Model.Important)
<br />
<h3>Остальные</h3>
}
@Html.Partial("PostHeadersTable", Model.Common)

<br />
Страница @(Model.Common.PageCount < Model.Common.PageNumber ? 0 : Model.Common.PageNumber) из @Model.Common.PageCount

@Html.PagedListPager(Model.Common, page => Url.Action("My", new { page, search = ViewBag.Search }))

ElderLists/FileCatalog/Views/Posts/New.cshtml
@model FileCatalog.Models.NewPostViewModel
@using FileCatalog.Extensions

@{
    ViewBag.Title = "Новая публикация";
}

<h2>@ViewBag.Title</h2>
<hr />

@using (Html.BeginForm("New", "Posts", FormMethod.Post, new { role = "form", enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary("", new { @class = "text-danger" })

        <div class="form-group">
            <h3>Информация</h3>

            <div class="form-group">
                @Html.LabelFor(model => model.Header, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.Header, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Header, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Text, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.Text, new { htmlAttributes = new { @class = "form-control", @rows = 4 } })
                    @Html.ValidationMessageFor(model => model.Text, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <h3>Метки</h3>

            <div class="form-group">
                @Html.LabelFor(model => model.IsHidden, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.IsHidden, new { htmlAttributes = new { @class = "form-control-static" } })
                </div>
            </div>

            @if (User.IsInRole("Moderator"))
            {
            <div class="form-group">
                @Html.LabelFor(model => model.IsImportant, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.IsImportant, new { htmlAttributes = new { @class = "form-control-static" } })
                </div>
            </div>
            }
        </div>

        <div class="form-group">
            <h3>Файлы</h3>
            <div class="form-group">
                <label class="control-label col-md-2">Добавить файлы</label>
                <div class="col-md-8">
                    <input type="file" name="files" class="form-control-static" multiple />
                </div>
            </div>
        </div>
    </div>
    <div class="form-horizontal">
        <div class="form-group">
            <div class="col-md-offset-2">
                <input type="submit" value="Создать" class="btn btn-default" />
            </div>
        </div>
    </div>
}

ElderLists/FileCatalog/Views/Posts/PostHeadersTable.cshtml
@model IEnumerable<FileCatalog.Models.PostHeaderViewModel>

<table class="table">
    <tr>
        <th>
            Название
        </th>
        <th>
            Опубликовано
        </th>
        <th>
            Автор
        </th>
        <th>
            Отредактировано
        </th>
        <th>
            Редактор
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @if (item.IsHidden)
                {
                    <i>[Скрыто] @Html.DisplayFor(modelItem => item.Header)</i>
                }
                else
                {
                    @Html.DisplayFor(modelItem => item.Header)
                }
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreationDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Author)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastEditDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Editor)
            </td>
            <td>
                @Html.ActionLink("Подробнее", "Details", "Posts", new { id = item.Id }, htmlAttributes: new { @class = "btn btn-default" })
                @Html.ActionLink("Автор", "Details", "Users", new { id = item.AuthorId }, htmlAttributes: new { @class = "btn btn-default" })
                @if (item.EditorId != null)
                {
                    @Html.ActionLink("Редактор", "Details", "Users", new { id = (int)item.EditorId }, htmlAttributes: new { @class = "btn btn-default" })
                }
            </td>
        </tr>
    }
</table>